# Use root/example as user/password credentials
version: '3.8'

services: 
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    container_name: "forex16d-client"
    ports:
      - "80:4200"
    volumes:
      - ./client:/app
      - /app/node_modules 
    command: "ng serve --host 0.0.0.0 --port 4200 --poll 1"

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: "forex16d-server"
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    command: "python -m flask run --debug --host=0.0.0.0"

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  postgres:
    image: postgres:latest
    container_name: forex16d-postgres
    environment:
      POSTGRES_DB: forex16d
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  node_modules:
  mongodb_data:
  postgres_data: