# Use root/example as user/password credentials
version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    container_name: "client"
    ports:
      - "80:4200"
    volumes:
      - ./client:/app
      - node_modules:/app/node_modules
    command: npm start

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: "server"
    ports:
      - "4090:3000"
    volumes:
      - ./server:/app
    command: "python main.py"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  node_modules:
  mongodb_data: